### ISSUE TITLE
RSS Icon in Sidebar disapears after Create new Note.

### ISSUE THREAD

**Issue by limex** [joethei/obsidian-rss#108] opened 2022-11-19 08:17 UTC
RSS Icon in Sidebar disapears after Create new Note.
Steps:
As you can see in this animated screen movie the rss icon is gone and only comes back after restarting the app.
Please advise with a workaround or fix if needed.

Thanks in advance
Thanks for your work in the plugin

BR Günther

![Screen Recording 2022-11-19 at 08 42 56 (1)](https://user-images.githubusercontent.com/1173039/202841620-56fd82fb-37a8-443d-b46b-7a22651832ec.gif)

**Comment by joethei** [comment] 2022-11-19 12:38
Duplicate of #95.
You can open the feed again by running the `RSS Reader: Open` command from the command pallete.
This issue got introduced as Obsidian 0.15 changed how the API for it works.
I have a fix ready, but I am working on a new version of the plugin that basically reworks the entire internals, so it will take a while for it to become available.

**Closed by joethei** 2022-11-19 12:38 UTC
Labels: duplicate
